### ISSUE TITLE
`Sentinel` is passed to `type_cast_value`

### ISSUE THREAD

**Issue by reallistic** [pallets/click#3069]
Starting in version 8.3.0, a `Sentinel` object is passed in to the `type_cast_value` function of the `Parameter` class and its derivatives if no value is supplied.

Reproduction:

```python
# cli_bug.py
import click


class CSVOption(click.Option):
    def type_cast_value(self, ctx, value):
        if value:
            return value.split(",")
        return value


@click.command(name="run")
@click.option("--csv", cls=CSVOption)
def main(csv):
    click.echo(f"{csv!r}")

if __name__ == "__main__":
    main()
```

```shell
$ uv run --with 'click==8.3.0' cli_bug.py

Installed 1 package in 1ms
Traceback (most recent call last):
  File "/home/coder/workspace/scratch/click-8_3_0-bug/cli_bug.py", line 17, in <module>
    main()
  File "/home/coder/.cache/uv/archive-v0/9Q5N3REh-YZUOJbO3iHRv/lib/python3.10/site-packages/click/core.py", line 1462, in __call__
    return self.main(*args, **kwargs)
  File "/home/coder/.cache/uv/archive-v0/9Q5N3REh-YZUOJbO3iHRv/lib/python3.10/site-packages/click/core.py", line 1382, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/coder/.cache/uv/archive-v0/9Q5N3REh-YZUOJbO3iHRv/lib/python3.10/site-packages/click/core.py", line 1206, in make_context
    self.parse_args(ctx, args)
  File "/home/coder/.cache/uv/archive-v0/9Q5N3REh-YZUOJbO3iHRv/lib/python3.10/site-packages/click/core.py", line 1217, in parse_args
    _, args = param.handle_parse_result(ctx, opts, args)
  File "/home/coder/.cache/uv/archive-v0/9Q5N3REh-YZUOJbO3iHRv/lib/python3.10/site-packages/click/core.py", line 2516, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/coder/.cache/uv/archive-v0/9Q5N3REh-YZUOJbO3iHRv/lib/python3.10/site-packages/click/core.py", line 2401, in process_value
    value = self.type_cast_value(ctx, value)
  File "/home/coder/workspace/scratch/click-8_3_0-bug/cli_bug.py", line 7, in type_cast_value
    return value.split(",")
AttributeError: 'Sentinel' object has no attribute 'split'
```

```shell
uv run --with 'click<8.3.0' cli_bug.py
None
```

Based on comments in #3065 and #3068 it would make sense to pass through `None` here given that this function is public. At a minimum, a changelog denoting the new behavior would be nice.

Environment:

- Python version: 3.10
- Click version: 8.3.0

**Comment by BronzeCrab** [comment]
Not only `uv` is broken, but `hatch` is also not working with 8.3.0:

```
$ hatch run lint:all
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.11/site-packages/hatch/cli/__init__.py:221 in main    │
│                                                                              │
│   218                                                                        │
│   219 def main():  # no cov                                                  │
│   220 │   try:                                                               │
│ ❱ 221 │   │   hatch(prog_name='hatch', windows_expand_args=False)            │
│   222 │   except Exception:  # noqa: BLE001                                  │
│   223 │   │   import sys                                                     │
│   224                                                                        │
│                                                                              │
│ /usr/local/lib/python3.11/site-packages/click/core.py:1462 in __call__       │
│                                                                              │
│ /usr/local/lib/python3.11/site-packages/click/core.py:1383 in main           │
│                                                                              │
│ /usr/local/lib/python3.11/site-packages/click/core.py:1850 in invoke         │
│                                                                              │
│ /usr/local/lib/python3.11/site-packages/click/core.py:1246 in invoke         │
│                                                                              │
│ /usr/local/lib/python3.11/site-packages/click/core.py:814 in invoke          │
│                                                                              │
│ /usr/local/lib/python3.11/site-packages/click/decorators.py:34 in new_func   │
│                                                                              │
│ /usr/local/lib/python3.11/site-packages/hatch/cli/run/__init__.py:147 in run │
│                                                                              │
│   144 │   elif not env_name:                                                 │
│   145 │   │   env_name = 'system'                                            │
│   146 │                                                                      │
│ ❱ 147 │   ctx.invoke(                                                        │
│   148 │   │   run_command,                                                   │
│   149 │   │   args=[command, *final_args],                                   │
│   150 │   │   env_names=[env_name],                                          │
│                                                                              │
│ /usr/local/lib/python3.11/site-packages/click/core.py:814 in invoke          │
│                                                                              │
│ /usr/local/lib/python3.11/site-packages/click/decorators.py:46 in new_func   │
│                                                                              │
│ /usr/local/lib/python3.11/site-packages/hatch/cli/env/run.py:123 in run      │
│                                                                              │
│   120 │   if filter_json:                                                    │
│   121 │   │   import json                                                    │
│   122 │   │                                                                  │
│ ❱ 123 │   │   filter_data = json.loads(filter_json)                          │
│   124 │   │   if not isinstance(filter_data, dict):                          │
│   125 │   │   │   app.abort('The --filter/-f option must be a JSON mapping') │
│   126                                                                        │
│                                                                              │
│ /usr/local/lib/python3.11/json/__init__.py:339 in loads                      │
│                                                                              │
│   336 │   │   │   │   │   │   │   │     s, 0)                                │
│   337 │   else:                                                              │
│   338 │   │   if not isinstance(s, (bytes, bytearray)):                      │
│ ❱ 339 │   │   │   raise TypeError(f'the JSON object must be str, bytes or by │
│   340 │   │   │   │   │   │   │   f'not {s.__class__.__name__}')             │
│   341 │   │   s = s.decode(detect_encoding(s), 'surrogatepass')              │
│   342                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: the JSON object must be str, bytes or bytearray, not Sentinel
```

**Comment by Rowlando13** [comment]
Thanks for the clear report. Should be None.

**Comment by Rowlando13** [comment]
@sirosen Thanks for helping with #3079 Would you mind taking a look at this?

**Comment by sirosen** [comment]
Yeah, I'll see if I can work out a fix for this one.

**Comment by Rowlando13** [comment]
Great!
