### ISSUE TITLE
`<nothing> not callable` error in Mypy with Click 8.1.0

### ISSUE THREAD

**Issue by NiklasRosenstein** [pallets/click#2227]
```py
# a.py
import click
@click.command()
def test():
  pass
test()
```

Run

```
$ mypy a.py
a.py:9: error: <nothing> not callable
Found 1 error in 1 file (checked 1 source file)
```

This used to pass with Click 8.0.4

Environment:

- Python version: 3.10.2
- Click version: 8.1.0

**Comment by Dreamsorcerer** [comment]
Looking at the code (https://github.com/pallets/click/blob/main/src/click/core.py#L1814), it appears to have been changed to a Union while adding support for not calling the decorator before the function.

As per the mypy documentation, this should be represented with overloads, rather than a union:
https://mypy.readthedocs.io/en/stable/generics.html?highlight=decorator#decorator-factories

**Comment by henryiii** [comment]
I think this is the same problem:


This MWE:

```python
import click

@click.group()
def main() -> None:
    pass

@main.command()
def tree() -> None:
    pass
```

Run with this noxfile:
```python
import nox

@nox.session
@nox.parametrize("click", ["8.0.4", "8.1.0"])
def mypy(session: nox.session, click: str) -> None:
    session.install("mypy==0.942", f"click=={click}")
    session.run("mypy", "--strict", "example.py")
```


Produces:

```console
$ nox
nox > Running session mypy(click='8.0.4')
nox > Creating virtual environment (virtualenv) using python3.10 in .nox/mypy-click-8-0-4
nox > python -m pip install mypy==0.942 click==8.0.4
nox > mypy --strict example.py
Success: no issues found in 1 source file
nox > Session mypy(click='8.0.4') was successful.
nox > Running session mypy(click='8.1.0')
nox > Creating virtual environment (virtualenv) using python3.10 in .nox/mypy-click-8-1-0
nox > python -m pip install mypy==0.942 click==8.1.0
nox > mypy --strict example.py
example.py:7: error: Untyped decorator makes function "tree" untyped
Found 1 error in 1 file (checked 1 source file)
nox > Command mypy --strict example.py failed with exit code 1
nox > Session mypy(click='8.1.0') failed.
nox > Ran multiple sessions:
nox > * mypy(click='8.0.4'): success
nox > * mypy(click='8.1.0'): failed
```

I'm guessing this was broken by #2212?

**Comment by mdellweg** [comment]
I am wondering if similar type annotations need to be added to `click.group()` and `click.Group.group()`.

**Comment by davidism** [comment]
Click 8.1.1 is now available: https://pypi.org/project/click/8.1.1/
