### ISSUE TITLE
typing.NoReturn is not available in Python 3.6.0

### ISSUE THREAD

**Issue by TTRh** [pallets/click#1882]
It seems that click has some deps issue with python 3.6 with the new release 8.0.0.
But still it seems supported : https://github.com/pallets/click/blob/main/setup.cfg#L33 

Is it expected behavior ? Or should python_requires be bump to 3.7 ?

how to reproduce : 

```
pyenv install 3.6.0
pyenv local 3.6.0
pip install click
python -c "import click"
```

```
AttributeError: module 'typing' has no attribute 'NoReturn'
```

**Comment by ThiefMaster** [comment]
Looks like it was added in 3.6.2...

**Comment by pkolbus** [comment]
I’m seeing this failure as well, via `black`. Still have 3.6.0 on some of our CI servers (for unfortunate reasons). It would be really nice if we could get a release that works with 3.6.0 even if the medium term solution is to focus on 3.6.2+.

The fix may be simple: add a `TYPE_CHECKING` guard. I’d be happy to contribute a PR.

**Comment by davidism** [comment]
Note that Python 3.6 (all versions) goes end of life in December 2021. You need to start upgrading your entire system very soon, for more important reasons than a typing import in Click.

**Comment by pkolbus** [comment]
Thanks!
