### ISSUE TITLE
Exception raised by ClickRunner with 7.1

### ISSUE THREAD

**Issue by hoefling** [pallets/click#1494]
My CI just pulled the 7.1 and the tests that use `mix_stderr=True` started to fail. Example to reproduce, pulled from [Testing](https://click.palletsprojects.com/en/7.x/testing/):

```python
# hello.py

import click

@click.command()
@click.argument('name')
def hello(name):
   click.echo('Hello %s!' % name)


if __name__ == '__main__':
    hello()
```
Test:

```python
# test_hello.py

from click.testing import CliRunner
from hello import hello

def test_hello():
    runner = CliRunner()
    result = runner.invoke(hello, ["fizz"], mix_stderr=True, catch_exceptions=False)
```

`pytest` output:

```
$ pytest
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.6.10, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /tmp/spam
collected 1 item                                                                                                                                                                                                  

test_hello.py F                                                                                                                                                                                             [100%]

==================================================================================================== FAILURES =====================================================================================================
___________________________________________________________________________________________________ test_hello ____________________________________________________________________________________________________

    def test_hello():
        runner = CliRunner()
>       result = runner.invoke(hello, ["fizz"], mix_stderr=True, catch_exceptions=False)

test_hello.py:6: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../foo/lib64/python3.6/site-packages/click/testing.py:329: in invoke
    cli.main(args=args or (), prog_name=prog_name, **extra)
../foo/lib64/python3.6/site-packages/click/core.py:781: in main
    with self.make_context(prog_name, args, **extra) as ctx:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Command hello>, info_name = 'hello', args = ['fizz'], parent = None, extra = {'mix_stderr': True}

    def make_context(self, info_name, args, parent=None, **extra):
        """This function when given an info name and arguments will kick
        off the parsing and create a new :class:`Context`.  It does not
        invoke the actual command callback though.
    
        :param info_name: the info name for this invokation.  Generally this
                          is the most descriptive name for the script or
                          command.  For the toplevel script it's usually
                          the name of the script, for commands below it it's
                          the name of the script.
        :param args: the arguments to parse as list of strings.
        :param parent: the parent context if available.
        :param extra: extra keyword arguments forwarded to the context
                      constructor.
        """
        for key, value in iteritems(self.context_settings):
            if key not in extra:
                extra[key] = value
>       ctx = Context(self, info_name=info_name, parent=parent, **extra)
E       TypeError: __init__() got an unexpected keyword argument 'mix_stderr'

../foo/lib64/python3.6/site-packages/click/core.py:698: TypeError
================================================================================================ 1 failed in 0.07s ================================================================================================
```
The example works with 7.0 though, so the temporary workaround is to blacklist the 7.1 in the dependencies list.

**Comment by hoefling** [comment]
Ok, I guess the `mix_stderr` arg was moved from `invoke` args to a `CliRunner` property, will have to rewrite the tests.

**Comment by davidism** [comment]
From the [changelog](https://click.palletsprojects.com/en/7.x/changelog/#version-7-1):

> Remove the unused `mix_stderr` parameter from `CliRunner.invoke`. #1435

This parameter was never doing anything, so you should be able to remove `mix_stderr=True` and continue testing. If you do want to control mixing stderr, `CliRunner(mix_stderr=False)` is what you want. Note that the default has always been true, so in your case you didn't need to pass it for that reason either.

**Comment by hoefling** [comment]
@davidism indeed - this is not a bug, but rather an invitation to review and clean up old tests.
