### ISSUE TITLE
Looks like `black` 22.1.0 does not work with `click` 8.1.0

### ISSUE THREAD

**Issue by portante** [pallets/click#2228]
In our CI jobs (see PR https://github.com/distributed-system-analysis/pbench/pull/2715), they fail with the following:

```
py run-test: commands[0] | black --check .
Traceback (most recent call last):
  File "/var/tmp/jenkins/tox/py/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "src/black/__init__.py", line 1423, in patched_main
  File "src/black/__init__.py", line 1409, in patch_click
ImportError: cannot import name '_unicodefun' from 'click' (/var/tmp/jenkins/tox/py/lib/python3.9/site-packages/click/__init__.py)
ERROR: InvocationError for command /var/tmp/jenkins/tox/py/bin/black --check . (exited with code 1)
```

Run `black` 22.1.0 with `click` 8.1.0.

`black` 22.1.0 should work with `click`.

Environment:

- Python version: Python 3.9
- Click version: 8.1.0

**Comment by portante** [comment]
Never mind.  `black` has already fixed the problem with 22.3.0.
